import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-library'
}

dependencies {
    implementation platform(SpringBootPlugin.BOM_COORDINATES)
    annotationProcessor platform(SpringBootPlugin.BOM_COORDINATES)
    testImplementation platform(SpringBootPlugin.BOM_COORDINATES)

    implementation project(':common')
    implementation project(':workspace')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation libs.swagger.annotations.jakarta
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation testFixtures(project(':common'))
    testImplementation project(':user')
    testImplementation testFixtures(project(':workspace'))
}
